# Generated by Django 4.2.16 on 2024-11-08 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_task_user_id_task_user_alter_task_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
